'use strict';
const BRANDS=[
 {name:'COLA',base:'#d71920',light:'#ff6358',dark:'#870c14',unlock:0},
 {name:'PEPZI',base:'#0759d8',light:'#57a0ff',dark:'#073275',unlock:0},
 {name:'FUNTI',base:'#f47c16',light:'#ffbb4b',dark:'#a94909',unlock:0},
 {name:'SPRYT',base:'#138f49',light:'#62c97c',dark:'#07532a',unlock:0},
 {name:'Dr. Popper',base:'#8c1737',light:'#d44e69',dark:'#4c0b20',unlock:28},
 {name:'SWEPS',base:'#efbd19',light:'#ffe26a',dark:'#98710b',unlock:65,ink:'#182317'},
 {name:'RED RULL',base:'#cfd4d9',light:'#ffffff',dark:'#58626d',unlock:774},
 {name:'Monstr',base:'#141414',light:'#414141',dark:'#020202',unlock:214},
 {name:'PRYME',base:'#f02d8d',light:'#ff83bd',dark:'#9c0e55',unlock:276},
 {name:'Poppy',base:'#efa0b7',light:'#ffd0dc',dark:'#a95470',unlock:584},
 {name:'San Aqua',base:'#8fd4f2',light:'#dbf6ff',dark:'#3a8bb5',unlock:108,ink:'#174d7d'},
 {name:'Mountain Brew',base:'#76c82b',light:'#b8ed68',dark:'#3a7716',unlock:344},
 {name:'NESTI',base:'#14afd2',light:'#7de8f5',dark:'#08708b',unlock:418},
 {name:'Liquid Dead',base:'#1d1d1f',light:'#545458',dark:'#030304',unlock:676},
 {name:'EVIEN',base:'#e5eff8',light:'#ffffff',dark:'#8da9c7',unlock:498,ink:'#20558c'},
 {name:'Grape Crushr',base:'#7027ae',light:'#b76be4',dark:'#3f126c',unlock:158}
];
const NEXT_UNLOCKS=BRANDS.filter(b=>b.unlock>0).sort((a,b)=>a.unlock-b.unlock);
const ROWS=6,COLS=5,CLEAR_AT=10,LAYER_STEP=3;
const MOTION={place:340,merge:335,mergeStagger:118,neighborPause:82,anticipation:165,collect:425,collectStagger:104,rewardPause:230};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const lerp=(a,b,t)=>a+(b-a)*t;
const ease=t=>t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2;
const game={board:Array.from({length:30},()=>[]),tray:[null,null,null],score:0,best:0,cleared:0,maxCombo:0,combo:0,selected:-1,busy:false,over:false,startAt:0,elapsed:0,lastTick:0,sound:true,pendingBrands:[],drag:null,chargeIndex:-1};
try{game.best=Math.max(Number(localStorage.getItem('cap-playtest-v04-best'))||0,Number(localStorage.getItem('cap-playtest-v03-best'))||0);const stored=localStorage.getItem('cap-playtest-v04-sound');game.sound=stored==null?localStorage.getItem('cap-playtest-v03-sound')!=='off':stored!=='off';}catch{}
function activeBrandIds(){return BRANDS.map((b,i)=>b.unlock<=game.cleared?i:-1).filter(i=>i>=0);}
function exposed(){return game.board.filter(s=>s.length).map(s=>s[s.length-1]);}
function run(s){if(!s||!s.length)return 0;const v=s[s.length-1];let n=0;for(let i=s.length-1;i>=0&&s[i]===v;i--)n++;return n;}
function emptyCount(){return game.board.reduce((n,s)=>n+(s.length===0),0);}
function neighbors(i){const x=i%COLS,y=Math.floor(i/COLS),a=[];if(y>0)a.push(i-COLS);if(x>0)a.push(i-1);if(x<COLS-1)a.push(i+1);if(y<ROWS-1)a.push(i+COLS);return a;}
function capHTML(id,bottom,index=0){const b=BRANDS[id],x=((index%3)-1)*.65;return `<div class="cap" data-brand="${id}" style="--base:${b.base};--light:${b.light};--dark:${b.dark};bottom:${bottom}px;transform:translateX(${x}px)"><span class="mark">${b.name}</span></div>`;}
function stackHTML(s){if(!s||!s.length)return '';let out='<div class="stack">';s.forEach((id,i)=>out+=capHTML(id,i*LAYER_STEP,i));return out+'</div>';}
function renderBoard(){const cells=$$('#grid .cell');game.board.forEach((s,i)=>{const c=cells[i];c.innerHTML=stackHTML(s);c.className='cell'+(s.length?'':' empty');const r=run(s);if(r===8)c.classList.add('pulse8');if(r===9)c.classList.add('pulse9');if(game.selected>=0&&!s.length)c.classList.add('target');if(game.chargeIndex===i)c.classList.add('charged');});$('#open').textContent=emptyCount();}
function renderTray(){const root=$('#tray');root.innerHTML='';game.tray.forEach((s,i)=>{const el=document.createElement('div');el.className='tray-slot'+(i===game.selected?' selected':'');el.dataset.index=i;el.innerHTML=s?stackHTML(s):'';root.appendChild(el);});}
function renderHUD(){$('#score').textContent=game.score.toLocaleString();$('#best').textContent=game.best.toLocaleString();$('#combo').textContent=game.combo>1?'x'+game.combo:'—';const soundBtn=$('#sound');if(soundBtn)soundBtn.textContent=game.sound?'Sound: on':'Sound: off';const active=activeBrandIds();$('#difficulty').textContent=`${active.length} CAPS ACTIVE`;const next=NEXT_UNLOCKS.find(b=>b.unlock>game.cleared);if(next){const prev=[0,...NEXT_UNLOCKS.map(b=>b.unlock)].filter(v=>v<=game.cleared).pop()||0,pct=clamp((game.cleared-prev)/(next.unlock-prev)*100,0,100);$('#unlockText').textContent=`${next.name} at ${next.unlock} cleared`;$('#progressFill').style.width=pct+'%';}else{$('#unlockText').textContent='All brands unlocked';$('#progressFill').style.width='100%';}}
function render(){renderBoard();renderTray();renderHUD();}
function saveBest(){game.best=Math.max(game.best,game.score);try{localStorage.setItem('cap-playtest-v04-best',String(game.best));}catch{}}
function chooseWeighted(arr){const total=arr.reduce((a,x)=>a+x.w,0);let r=Math.random()*total;for(const x of arr){r-=x.w;if(r<=0)return x.id;}return arr[arr.length-1].id;}
function makeStack(forceBrand=null){const ids=activeBrandIds(),tops=exposed(),early=game.elapsed<180000;let brand=forceBrand;if(brand==null){const weights=ids.map(id=>({id,w:1}));for(const id of tops){const w=weights.find(x=>x.id===id);if(w)w.w+=early?3.4:2;}game.board.forEach(s=>{if(!s.length)return;const id=s[s.length-1],r=run(s),w=weights.find(x=>x.id===id);if(w&&r>=6&&r<10)w.w+=4+r*.8;});brand=chooseWeighted(weights);}const n=early?4+Math.floor(Math.random()*3):2+Math.floor(Math.random()*4),s=Array(n).fill(brand),mixChance=early?.17:Math.min(.5,.28+ids.length*.015);if(ids.length>1&&n>=4&&Math.random()<mixChance){let under=brand;while(under===brand)under=ids[Math.floor(Math.random()*ids.length)];for(let i=0;i<Math.min(2,n-2);i++)s[i]=under;}return s;}
function refillTray(){const forced=game.pendingBrands.splice(0,3);game.tray=[0,1,2].map(i=>makeStack(forced[i]??null));}
function showBanner(name){return new Promise(resolve=>{const el=$('#banner');$('#bannerName').textContent=name;el.classList.add('show');setTimeout(()=>{el.classList.remove('show');setTimeout(resolve,220);},1250);});}
async function processUnlocks(){let shown=0;try{shown=Number(sessionStorage.getItem('cap-playtest-v04-lastUnlock')||0);}catch{}const fresh=NEXT_UNLOCKS.filter(b=>b.unlock>shown&&b.unlock<=game.cleared);for(const b of fresh){game.pendingBrands.push(BRANDS.indexOf(b));sfx('unlock');await showBanner(b.name);shown=b.unlock;try{sessionStorage.setItem('cap-playtest-v04-lastUnlock',String(shown));}catch{}}}
let ac=null;
function audioContext(){if(!game.sound)return null;try{if(!ac)ac=new (window.AudioContext||window.webkitAudioContext)();if(ac.state==='suspended')ac.resume();return ac;}catch{return null;}}
function voice({freq=440,to=freq,dur=.08,gain=.015,type='sine',delay=0}){const c=audioContext();if(!c)return;const now=c.currentTime+delay,o=c.createOscillator(),g=c.createGain();o.type=type;o.connect(g);g.connect(c.destination);o.frequency.setValueAtTime(freq,now);o.frequency.exponentialRampToValueAtTime(Math.max(35,to),now+dur);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(gain,now+.006);g.gain.exponentialRampToValueAtTime(.0001,now+dur);o.start(now);o.stop(now+dur+.02);}
function sfx(kind,step=0,combo=1){if(!game.sound)return;if(kind==='land'){voice({freq:235,to:145,dur:.11,gain:.028,type:'triangle'});voice({freq:520,to:410,dur:.07,gain:.009,delay:.01});return;}if(kind==='merge'){const shift=1+Math.min(step,5)*.018;voice({freq:610*shift,to:470*shift,dur:.065,gain:.014,type:'sine'});voice({freq:880*shift,to:690*shift,dur:.052,gain:.0055,type:'triangle',delay:.005});return;}if(kind==='collect'){const shift=1+Math.min(step,7)*.012;voice({freq:410*shift,to:315*shift,dur:.075,gain:.016,type:'triangle'});voice({freq:720*shift,to:600*shift,dur:.05,gain:.006,delay:.008});return;}if(kind==='charge'){voice({freq:255,to:390,dur:.15,gain:.012,type:'sine'});return;}if(kind==='reward'){const root=combo>1?440:392;[1,1.25,1.5].forEach((r,i)=>voice({freq:root*r,to:root*r,dur:.24+i*.025,gain:.017+i*.002,type:i===0?'triangle':'sine',delay:i*.035}));voice({freq:160,to:105,dur:.18,gain:.018,type:'triangle'});return;}if(kind==='unlock'){[523.25,659.25,783.99].forEach((f,i)=>voice({freq:f,to:f,dur:.18,gain:.018,delay:i*.055}));return;}if(kind==='bad'){voice({freq:155,to:105,dur:.12,gain:.022,type:'triangle'});return;}}
function vibrate(pattern){try{navigator.vibrate?.(pattern);}catch{}}
function capSize(){return parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--cap'))||56;}
function cellCenterEl(i){const r=$$('#grid .cell')[i].getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height*.72};}
function trayCenterEl(i){const r=$$('#tray .tray-slot')[i].getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height*.67};}
function collectorCenter(){const r=$('#collectorMouth').getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2};}
function makeFlyingCap(id,start){const el=document.createElement('div'),b=BRANDS[id],size=capSize();el.className='cap flying';el.dataset.brand=id;el.style.cssText+=`--base:${b.base};--light:${b.light};--dark:${b.dark};left:${start.x-size/2}px;top:${start.y-size/2}px`;el.innerHTML=`<span class="mark">${b.name}</span>`;document.body.appendChild(el);return el;}
function animateCap(el,start,end,{duration=MOTION.merge,arc=34,scaleEnd=1,rotation=.04,fadeEnd=1}={}){return new Promise(resolve=>{const t0=performance.now();function frame(now){const raw=clamp((now-t0)/duration,0,1),e=ease(raw),x=lerp(start.x,end.x,e),baseY=lerp(start.y,end.y,e),lift=Math.sin(raw*Math.PI)*arc,y=baseY-lift,scale=1+(scaleEnd-1)*e+Math.sin(raw*Math.PI)*.025;el.style.transform=`translate(${x-start.x}px,${y-start.y}px) scale(${scale}) rotate(${rotation*e}turn)`;el.style.opacity=String(1+(fadeEnd-1)*e);if(raw<1)requestAnimationFrame(frame);else resolve();}requestAnimationFrame(frame);});}
async function flyCap(id,start,end,opts={}){const el=makeFlyingCap(id,start);await animateCap(el,start,end,opts);el.remove();}
function microBump(i){const c=$$('#grid .cell')[i];if(!c)return;c.classList.remove('micro-bump');void c.offsetWidth;c.classList.add('micro-bump');setTimeout(()=>c.classList.remove('micro-bump'),220);}
function collectorHit(){const c=$('#collector');c.classList.remove('hit');void c.offsetWidth;c.classList.add('hit');setTimeout(()=>c.classList.remove('hit'),250);}
function collectorReward(){const c=$('#collector');c.classList.remove('reward');void c.offsetWidth;c.classList.add('reward');setTimeout(()=>c.classList.remove('reward'),540);}
function rewardPop(label){const r=$('#collector').getBoundingClientRect(),el=document.createElement('div');el.className='reward-pop';el.textContent=label;el.style.left=(r.left+r.width/2)+'px';el.style.top=(r.bottom-8)+'px';document.body.appendChild(el);setTimeout(()=>el.remove(),950);}
async function landStack(trayIndex,cellIndex,stack,origin=null){const source=origin||trayCenterEl(trayIndex),target=cellCenterEl(cellIndex),ghost=document.createElement('div');ghost.className='ghost';ghost.style.left=source.x+'px';ghost.style.top=source.y+'px';ghost.innerHTML=stackHTML(stack);document.body.appendChild(ghost);const t0=performance.now();await new Promise(resolve=>{function frame(now){const raw=clamp((now-t0)/MOTION.place,0,1),e=ease(raw),x=lerp(source.x,target.x,e),baseY=lerp(source.y,target.y-15,e),lift=Math.sin(raw*Math.PI)*34,y=baseY-lift,scale=1+Math.sin(raw*Math.PI)*.035;ghost.style.left=x+'px';ghost.style.top=y+'px';ghost.style.transform=`translate(-50%,-70%) scale(${scale})`;if(raw<1)requestAnimationFrame(frame);else resolve();}requestAnimationFrame(frame);});ghost.remove();sfx('land');vibrate(6);microBump(cellIndex);await wait(72);}
async function transferRun(from,to,count){const targetBase=game.board[to].length,promises=[];for(let k=0;k<count;k++){const src=game.board[from];if(!src.length)break;const id=src[src.length-1],start=cellCenterEl(from),end=cellCenterEl(to);start.y-=Math.max(0,(src.length-1)*LAYER_STEP);end.y-=Math.max(0,(targetBase+k)*LAYER_STEP);src.pop();renderBoard();const p=flyCap(id,start,end,{duration:MOTION.merge,arc:32,scaleEnd:1,rotation:(k%2?-.028:.028)}).then(()=>{game.board[to].push(id);renderBoard();microBump(to);sfx('merge',k);vibrate(2);});promises.push(p);if(k<count-1)await wait(MOTION.mergeStagger);}await Promise.all(promises);await wait(MOTION.neighborPause);}
async function clearTop(index,count,comboNo){game.combo=comboNo;game.chargeIndex=index;render();sfx('charge');await wait(MOTION.anticipation);const mult=1+.25*(comboNo-1),totalPoints=Math.round(count*10*mult),baseScore=game.score,cellRect=$$('#grid .cell')[index].getBoundingClientRect(),promises=[];for(let k=0;k<count;k++){const s=game.board[index];if(!s.length)break;const id=s[s.length-1],start={x:cellRect.left+cellRect.width/2,y:cellRect.top+cellRect.height*.72-Math.max(0,(s.length-1)*LAYER_STEP)},mouth=collectorCenter(),end={x:mouth.x+((k%3)-1)*2.5,y:mouth.y+(k%2?1:-1)};s.pop();renderBoard();const prev=Math.round(totalPoints*k/count),next=Math.round(totalPoints*(k+1)/count),inc=next-prev;const p=flyCap(id,start,end,{duration:MOTION.collect,arc:55,scaleEnd:.34,rotation:(k%2?-.18:.18),fadeEnd:.72}).then(()=>{game.score+=inc;saveBest();renderHUD();collectorHit();sfx('collect',k);vibrate(2);});promises.push(p);if(k<count-1)await wait(MOTION.collectStagger);}await Promise.all(promises);game.chargeIndex=-1;game.cleared+=count;game.maxCombo=Math.max(game.maxCombo,comboNo);saveBest();render();collectorReward();sfx('reward',0,comboNo);vibrate(comboNo>1?[6,20,8]:8);rewardPop(comboNo>1?`COMBO x${comboNo} · +${totalPoints}`:`CLEAR · +${totalPoints}`);await wait(MOTION.rewardPause);game.score=baseScore+totalPoints;saveBest();renderHUD();}
async function resolve(start){const queue=[start],pending=new Set(queue);let comboNo=0;const enqueue=i=>{if(game.board[i].length&&!pending.has(i)){queue.push(i);pending.add(i);}};while(queue.length){const target=queue.shift();pending.delete(target);if(!game.board[target].length)continue;for(const source of neighbors(target)){const dst=game.board[target],src=game.board[source];if(!src.length||!dst.length||src[src.length-1]!==dst[dst.length-1])continue;const n=run(src);await transferRun(source,target,n);if(src.length)enqueue(source);}const st=game.board[target],r=run(st);if(r>=CLEAR_AT){comboNo++;await clearTop(target,r,comboNo);enqueue(target);}}game.combo=comboNo;renderHUD();return comboNo;}
function reject(cellIndex){const c=$$('#grid .cell')[cellIndex];c?.classList.add('bad');setTimeout(()=>c?.classList.remove('bad'),350);sfx('bad');}
async function place(trayIndex,cellIndex,origin=null){if(game.busy||game.over)return false;const stack=game.tray[trayIndex];if(!stack||game.board[cellIndex].length){reject(cellIndex);return false;}if(!game.startAt){game.startAt=performance.now();game.lastTick=game.startAt;}game.busy=true;game.selected=-1;const moving=stack.slice();game.tray[trayIndex]=null;render();await landStack(trayIndex,cellIndex,moving,origin);game.board[cellIndex]=moving;renderBoard();await resolve(cellIndex);await processUnlocks();if(game.tray.every(x=>!x))refillTray();game.busy=false;game.over=emptyCount()===0;render();if(game.over){$('#finalScore').textContent=game.score.toLocaleString();$('#finalStats').textContent=`${game.cleared} caps cleared · max combo x${Math.max(1,game.maxCombo)}`;$('#overOverlay').hidden=false;}return true;}
function selectTray(i){if(game.busy||!game.tray[i])return;game.selected=game.selected===i?-1:i;render();}
function setupBoard(){const g=$('#grid');g.innerHTML='';for(let i=0;i<30;i++){const c=document.createElement('div');c.className='cell empty';c.dataset.index=i;c.addEventListener('click',()=>{if(game.selected>=0)place(game.selected,i)});g.appendChild(c);}}
function startGame(){game.board=Array.from({length:30},()=>[]);game.score=0;game.cleared=0;game.maxCombo=0;game.combo=0;game.selected=-1;game.busy=false;game.over=false;game.pendingBrands=[];game.chargeIndex=-1;game.startAt=0;game.lastTick=performance.now();game.elapsed=0;try{sessionStorage.setItem('cap-playtest-v04-lastUnlock','0');}catch{}refillTray();render();$('#overOverlay').hidden=true;}
let dragState=null;
document.addEventListener('pointerdown',e=>{const slot=e.target.closest('.tray-slot');if(!slot||game.busy)return;const i=+slot.dataset.index;if(!game.tray[i])return;dragState={i,x:e.clientX,y:e.clientY,moved:false,ghost:null};slot.setPointerCapture?.(e.pointerId);});
document.addEventListener('pointermove',e=>{if(!dragState)return;const d=dragState;if(!d.moved&&Math.hypot(e.clientX-d.x,e.clientY-d.y)>7){d.moved=true;d.ghost=document.createElement('div');d.ghost.className='ghost';d.ghost.innerHTML=stackHTML(game.tray[d.i]);document.body.appendChild(d.ghost);}if(d.ghost){d.ghost.style.left=e.clientX+'px';d.ghost.style.top=e.clientY+'px';}});
document.addEventListener('pointerup',e=>{if(!dragState)return;const d=dragState;if(d.ghost)d.ghost.remove();dragState=null;if(d.moved){const el=document.elementFromPoint(e.clientX,e.clientY)?.closest('.cell');if(el)place(d.i,+el.dataset.index,{x:e.clientX,y:e.clientY});else sfx('bad');}else selectTray(d.i);});
$('#sound').onclick=()=>{game.sound=!game.sound;try{localStorage.setItem('cap-playtest-v04-sound',game.sound?'on':'off');}catch{}renderHUD();};
$('#help').onclick=()=>$('#helpOverlay').hidden=false;$('#closeHelp').onclick=()=>$('#helpOverlay').hidden=true;
$('#again').onclick=startGame;$('#closeOver').onclick=()=>$('#overOverlay').hidden=true;
document.addEventListener('keydown',e=>{if(e.key>='1'&&e.key<='3'){selectTray(+e.key-1);return;}if(e.key.toLowerCase()==='m'){$('#sound').click();}});
setInterval(()=>{const now=performance.now(),active=game.startAt&&!game.over&&!document.hidden&&$('#helpOverlay').hidden;if(active)game.elapsed+=Math.max(0,now-(game.lastTick||now));game.lastTick=now;const sec=Math.floor(game.elapsed/1000);$('#time').textContent=Math.floor(sec/60)+':'+String(sec%60).padStart(2,'0');},250);
setupBoard();startGame();
